#threshold: 3
#frequency: 60
#timeout: 20

notifiers:

  email-admins:
    handler: smtp
    extra:
      to: admins@example.com
      from: root@localhost

  emit-to-stdout:
    handler: stdout


checks:

  iana-desire-200:
    collector: http
    handler: http_code
    timeout: 25
    frequency: 3
    threshold: 3
    notifiers:
      - email-admins
      - emit-to-stdout
    extra:
      uri: http://www.iana.org/domains/reserved

  iana-desire-404:
    collector: http
    handler: http_code
    timeout: 25
    frequency: 3
    threshold: 3
    notifiers:
      - email-admins
      - emit-to-stdout
    extra:
      uri: http://www.iana.org/domains/reserved/example-404
      desired_codes:
        - 404
