checks:

  http:

      linkpeek.com:
        uri: https://linkpeek.com/
        handler: http_code
        desired_codes:
          - 200
        timeout: 25
        frequency: 6
        threshold: 3

      example.com-404:
        uri: https://example.com/49d8mc749x871
        handler: http_code
        desired_codes:
          - 404
        timeout: 25
        frequency: 3
        threshold: 3
