#threshold: 3
#frequency: 60
#timeout: 20

checks:

  linkpeek.com:
    collector: http
    handler: http_code
    extra:
      uri: https://linkpeek.com/
      desired_codes:
        - 200
    timeout: 25
    frequency: 3
    threshold: 3

  example.com-i-desire-404:
    collector: http
    handler: http_code
    extra:
      uri: https://example.com/49d8mc749x871
      desired_codes:
        - 404

  example.com-i-desire-200-but-end-up-with-404:
    collector: http
    handler: http_code
    extra:
      uri: https://example.com/49d8mc749x871
