#threshold: 3
#frequency: 60
#timeout: 20

notifiers:

  email-admins:
    handler: smtp
    extra:
      to: admins@example.com
      from: root@localhost

  emit-to-stdout:
    handler: stdout

checks:

  example.com-i-desire-404:
    collector: http
    handler: http_code
    timeout: 25
    frequency: 3
    threshold: 3
    notifiers:
      - email-admins
      - emit-to-stdout
    extra:
      uri: https://example.com/49d8mc749x871
      desired_codes:
        - 404

  example.com-i-desire-200-but-end-up-with-404:
    collector: http
    handler: http_code
    extra:
      uri: https://example.com/49d8mc749x871
    notifiers:
      - emit-to-stdout
